apiVersion: apps/v1
kind: Deployment
metadata:
  name: golf-fields
  namespace: golf-fields
  labels:
    app: golf-fields 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golf-fields
  template:
    metadata:
      labels:
        app: golf-fields
    spec:               
      containers:
        - name: golf-fields
          image: tetianaworkplace/golffields:latest
          resources:
            limits:
              memory: "1024Mi"              
          ports:
            - containerPort: 5030
          env:
            - name: TCP_HOST
              value: "{TCP_HOST}"
            - name: DB_HOST
              value: "{DB_HOST}"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: golf-fields-service  
  namespace: golf-fields
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 5030
      targetPort: 5030
  selector:
    app: golf-fields
