apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: mssqldb       
          persistentVolumeClaim:
            claimName: pvc-mssql
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2017-CU21-ubuntu-16.04
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Developer"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql-db-password 
                key: password
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
      
---
apiVersion: v1
kind: Service
metadata:
  name: mssqlsvc
  namespace: database
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
