apiVersion: apps/v1
kind: Deployment
metadata:
  name: golf-fields-api
  namespace: golf-fields-api
  labels:
    app: golf-fields-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golf-fields-api
  template:
    metadata:
      labels:
        app: golf-fields-api
    spec:               
      containers:
        - name: golf-fields-api
          image: tetianaworkplace/golffieldsapi-test:latest
          resources:
            limits:
              memory: "1024Mi"              
          ports:
            - containerPort: 5000
          env:
            - name: TCP_HOST
              value: "{TCP_HOST}"
            - name: DB_HOST
              value: "{DB_HOST}"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: golf-fields-api-service  
  namespace: golf-fields-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: golf-fields-api
