apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: database
  labels:
    purpose: mssql
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
--- 
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mssql-pv
  namespace: database
  labels:
    type: localPath
    purpose: mssql
spec:
  storageClassName: local-storage
  local:
    path: /
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mssql
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Gi  
  selector:
    matchLabels:
      purpose: mssql
  